### ISSUE TITLE
cargo build: waiter_codegen v1.6.4: could not find `export` in `syn`

### ISSUE THREAD

**Issue by tYYGH** [dmitryb-dev/waiter#4] opened 2021-02-15 21:20 UTC
I get this error when building my project, where I try to add `waiter_ci` in `Cargo.toml`:

```
   Compiling waiter_codegen v1.6.4
error[E0432]: unresolved import `syn::export`
 --> /home/yves/.cargo/registry/src/github.com-1ecc6299db9ec823/waiter_codegen-1.6.4/src/lib.rs:7:10
  |
7 | use syn::export::{TokenStream2, ToTokens};
  |          ^^^^^^ could not find `export` in `syn`

[× many times…]

error: cannot determine resolution for the macro `quote::quote`
  --> /home/yves/.cargo/registry/src/github.com-1ecc6299db9ec823/waiter_codegen-1.6.4/src/component/mod.rs:80:18
   |
80 |     let result = quote::quote! {
   |                  ^^^^^^^^^^^^
   |
   = note: import resolution is stuck, try simplifying macro imports

[× many times…]
```

**Comment by dmitryb-dev** [comment] 2021-04-25 17:30
Must be fixed by [khooj fix](https://github.com/dmitryb-dev/waiter/pull/5). Reopen please if issue persists since I couldn't reproduce it

**Closed as completed by dmitryb-dev** 2021-04-25 17:30 UTC
